name: search
description: A new Flutter package project.
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  foundation:
    path: "./../../foundation"
  fairplay_ds:
    path: "./../../fairplay_ds"
  injectable: 1.5.3
  provider: ^6.0.3
  uuid: ^3.0.6
  flutter_bloc: 8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
